export const siteConfig = {
  name: "Erb Family Wellness",
  shortName: "Erb Family Wellness",
  tagline: "The Greatest Place of Hope and Healing",
  description:
    "Erb Family Wellness in Coppell, TX offers corrective chiropractic care, SoftWave therapy, spinal decompression, hyperbaric oxygen therapy, and more. Serving families since 1998.",
  url: "https://www.erbfamilywellness.com",
  phone: "(972) 393-6262",
  email: "derb@erbfamilywellness.com",
  address: {
    street: "255 S Denton Tap Rd, Suite 200",
    city: "Coppell",
    state: "TX",
    zip: "75019",
    full: "255 S Denton Tap Rd, Suite 200, Coppell, TX 75019",
  },
  doctor: {
    name: "Dr. David Erb",
    credentials: "DC",
    experience: "Since 1998",
  },
  hours: {
    monday: "8:00 AM - 10:30 AM, 3:30 PM - 6:00 PM",
    tuesday: "12:00 PM - 3:00 PM",
    wednesday: "8:00 AM - 10:30 AM, 3:30 PM - 6:00 PM",
    thursday: "2:30 PM - 5:30 PM",
    friday: "7:30 AM - 10:30 AM",
    saturday: "Closed",
    sunday: "Closed",
  },
  social: {
    facebook: "https://www.facebook.com/ErbFamilyCoppell",
    instagram: "https://www.instagram.com/erbfamilywellness/",
    rumble: "https://rumble.com/c/ErbFamilyWellness",
    linkedin: "https://www.linkedin.com/in/drdaviderb/",
  },
  services: [
    { name: "Chiropractic Care", slug: "chiropractic-care" },
    { name: "Spinal Correction", slug: "spinal-correction" },
    { name: "SoftWave Therapy", slug: "softwave-therapy" },
    { name: "Spinal Decompression", slug: "spinal-decompression" },
    { name: "Neuropathy Treatment", slug: "neuropathy-treatment" },
    { name: "Hyperbaric Oxygen Therapy", slug: "hyperbaric-oxygen-therapy" },
    { name: "Whole Body Thermography", slug: "thermography" },
    { name: "Pediatric Chiropractic", slug: "pediatric-chiropractic" },
    { name: "Prenatal Chiropractic", slug: "prenatal-chiropractic" },
    { name: "Back Pain Treatment", slug: "back-pain-treatment" },
    { name: "Neck Pain Treatment", slug: "neck-pain-treatment" },
    { name: "Sciatica Treatment", slug: "sciatica-treatment" },
  ],
  serviceArea: [
    "Coppell",
    "Lewisville",
    "Flower Mound",
    "Carrollton",
    "Grapevine",
    "Irving",
    "Southlake",
    "Valley Ranch",
    "Las Colinas",
    "Dallas",
  ],
} as const;
